#ifndef slic3r_Changelog_hpp_
#define slic3r_Changelog_hpp_

// Data model for the in-app changelog viewer.
//
// The application ships resources/changelog/changelog.json, generated by
// scripts/changelog/export-app-changelog.mjs from the repository's published
// releases and the commits between their tags. This header is deliberately
// free of wxWidgets so the parsing, date handling, filtering and export logic
// can be unit-tested (tests/changelog) without a GUI.

#include <functional>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

namespace Slic3r::Changelog {

// A calendar date with no time zone. Release dates are the UTC calendar day of
// the publication instant, exactly as the exporter wrote them.
struct CivilDate
{
    int year  = 0;
    int month = 0; // 1..12
    int day   = 0; // 1..days_in_month

    static bool is_leap_year(int year);
    static int  days_in_month(int year, int month);
    bool        is_valid() const;

    // Parses a strict ISO-8601 calendar date "YYYY-MM-DD" (also "YYYY/MM/DD"
    // and "YYYY.MM.DD"). Partial input such as "2026-09" or "2026" is
    // rejected: a filter must never guess the missing part.
    static std::optional<CivilDate> from_iso(std::string_view text);
    std::string                     to_iso() const;

    // Serial day number (proleptic Gregorian), for ordering and day arithmetic.
    long      to_days() const;
    static CivilDate from_days(long days);
    CivilDate plus_days(long delta) const { return from_days(to_days() + delta); }
};

bool operator==(const CivilDate &a, const CivilDate &b);
bool operator!=(const CivilDate &a, const CivilDate &b);
bool operator<(const CivilDate &a, const CivilDate &b);
bool operator<=(const CivilDate &a, const CivilDate &b);
bool operator>(const CivilDate &a, const CivilDate &b);
bool operator>=(const CivilDate &a, const CivilDate &b);

// Field order of the user's locale short date format, used to read a typed
// date such as "8/9/2026" without guessing whether 8 is the day or the month.
enum class DateOrder { YearMonthDay, DayMonthYear, MonthDayYear };

// Accepts what a person types into the date filter: the ISO form (always,
// whatever the locale) or three numeric fields separated by '/', '-', '.' or
// spaces in the locale's order with a four-digit year. Anything else —
// partial input, two-digit years, out-of-range fields, February 30th — yields
// no date, and the caller keeps the typed text on screen with an inline error.
std::optional<CivilDate> parse_typed_date(std::string_view text, DateOrder order);

// One commit line under a release.
struct Entry
{
    std::string sha;       // full 40-hex commit id
    std::string short_sha; // first 9 characters
    std::string text;      // commit subject
    std::string category;  // added | changed | fixed | removed | documented
};

// One published release.
struct Release
{
    std::string        tag;
    std::string        version;  // "v102"
    int                ordinal = 0;
    CivilDate          date;
    std::string        published; // ISO-8601 instant
    std::string        code_name_en;
    std::string        code_name_yue;
    std::string        qualifier;
    std::string        url;
    std::string        commit;
    std::string        build;
    bool               prerelease  = false;
    bool               baseline    = false; // oldest release: no earlier tag to diff against
    bool               same_commit = false; // tag points at the previous release's commit
    std::vector<Entry> entries;
};

struct Document
{
    int                  schema = 0;
    std::string          repository;
    std::string          commit_url_template; // "https://github.com/<repo>/commit/{sha}"
    std::string          generated;
    std::string          category_derivation;
    std::vector<Release> releases; // newest first, as exported
};

// Parses the exporter's JSON. Throws std::runtime_error with a message that
// names the offending field when the document is malformed: a missing file
// and a corrupt file are both surfaced to the user rather than rendered as an
// empty changelog.
Document parse_document(const std::string &json_text);

// Reads and parses a JSON file; the same error contract as parse_document.
Document load_document(const std::string &path);

// Substitutes {sha} in the document's template.
std::string commit_url(const Document &document, const std::string &sha);

// Inclusive calendar-day bounds; an unset bound is open.
struct DateRange
{
    std::optional<CivilDate> from;
    std::optional<CivilDate> to;

    bool is_unbounded() const { return !from && !to; }
    bool contains(const CivilDate &date) const;
    // Human-readable description for the export header ("2026-01-01 to 2026-09-08",
    // "from 2026-01-01", "until 2026-09-08", "all versions").
    std::string describe() const;

    static DateRange all();
    static DateRange last_days(const CivilDate &today, int days); // today-days+1 .. today
    static DateRange this_year(const CivilDate &today);
};

// Text predicate supplied by the caller (the GUI hands in its SearchField
// matcher so plain-text and regex modes both work here). A null matcher
// matches everything.
using TextMatcher = std::function<bool(const std::string &)>;

struct FilteredRelease
{
    const Release            *release = nullptr;
    std::vector<const Entry *> entries; // the entries that survived the filter
};

// Applies the date range to releases and the text matcher to entry text.
// A release whose own version, tag or code name matches keeps all of its
// entries. A release inside the range with no matching entry is dropped, and
// so is one with no entries at all while a text filter is active.
std::vector<FilteredRelease> filter_releases(const Document &document, const DateRange &range,
                                             const TextMatcher &matcher);

std::size_t count_entries(const std::vector<FilteredRelease> &releases);

enum class ExportFormat { Markdown, PlainText };

// Serializes the filtered view. The header states the repository, the
// exported date range, the active search (if any) and the counts; every entry
// keeps its full SHA so a copied changelog stays traceable.
std::string export_text(const Document &document, const std::vector<FilteredRelease> &releases,
                        const DateRange &range, const std::string &search_description,
                        ExportFormat format);

} // namespace Slic3r::Changelog

#endif // slic3r_Changelog_hpp_
