#!/usr/bin/env node
/*
 * Assembles the Bambu Studio UI kit into a self-contained page.
 *
 *   node ui-md3/scripts/assemble-ui-kit.mjs --check|--write
 *
 * The kit's index.html carried a header comment promising an assembler for
 * years without one existing: the twelve .jsx sources and the page that inlines
 * them were kept in step by hand. This is that assembler. It compiles each
 * source with ui-md3/scripts/jsx-transform.mjs and writes the result between
 * the ASSEMBLED markers in index.html, leaving the surrounding shell — the
 * design-system card metadata, the head, the mount point — hand-editable.
 *
 * What the page loses in the process is every third-party request. It used to
 * pull React, ReactDOM and @babel/standalone from unpkg and compile its own
 * source in the visitor's browser, which meant three requests off-site, 2.7 MB
 * of compiler, and a completely blank page whenever unpkg was slow, blocked or
 * down. React now ships from vendor/ beside the page and the JSX is compiled
 * here, so the kit matches the rest of the site: everything served from this
 * repository and nothing from anywhere else.
 *
 * --check is the CI gate, alongside assemble-index.mjs --check: an edited .jsx
 * that was never re-assembled fails the deploy instead of publishing a page
 * whose behaviour nobody reviewed.
 */

import { readFile, writeFile, access } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { transform } from './jsx-transform.mjs';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const kitDir = path.resolve(scriptDir, '..', 'design-system', 'ui_kits', 'bambu-studio');
const indexPath = path.join(kitDir, 'index.html');

// Load order matters and is not alphabetical: Components defines the MD
// primitives every screen destructures, the screens register themselves on
// window.Screens, Overlays registers the dialogs, and App mounts the tree.
const SOURCES = [
  'Components.jsx',
  'Home.jsx',
  'Prepare.jsx',
  'Preview.jsx',
  'Device.jsx',
  'Multi.jsx',
  'Project.jsx',
  'Calibration.jsx',
  'Filament.jsx',
  'Settings.jsx',
  'Overlays.jsx',
  'App.jsx',
];

// The compiled blocks are classic scripts sharing one global scope, so a
// top-level const declared twice is a SyntaxError that silently kills every
// script after it. Babel used to hide this by rewriting const to var; nothing
// hides it now, so the assembler checks for it.
const TOP_LEVEL_DECLARATION = /^(?:const|let|class)\s+(?:\{[^}]*\}|[A-Za-z_$][\w$]*)/gm;
const BINDING_NAME = /(?:^|[{,\s])([A-Za-z_$][\w$]*)\s*(?::\s*([A-Za-z_$][\w$]*))?/g;

const START = '<!-- ASSEMBLED: everything below is generated by ui-md3/scripts/assemble-ui-kit.mjs -->';
const END = '<!-- END ASSEMBLED -->';

const checkOnly = process.argv.includes('--check');
const writeRequested = process.argv.includes('--write');
if (!checkOnly && !writeRequested) {
  console.error('Usage: node ui-md3/scripts/assemble-ui-kit.mjs --check|--write');
  process.exit(2);
}

const original = await readFile(indexPath, 'utf8');
const eol = original.includes('\r\n') ? '\r\n' : '\n';
const shell = original.replace(/\r\n/g, '\n');

const startAt = shell.indexOf(START);
const endAt = shell.indexOf(END);
if (startAt === -1 || endAt === -1 || endAt < startAt) {
  throw new Error(`${path.relative(process.cwd(), indexPath)} is missing its ASSEMBLED markers`);
}

// The page must reach React locally. A head that has drifted back to a CDN is
// the exact regression this script exists to prevent, so it is an error here as
// well as in the layout gate.
const head = shell.slice(0, startAt);
for (const vendored of ['vendor/react.production.min.js', 'vendor/react-dom.production.min.js']) {
  if (!head.includes(vendored)) {
    throw new Error(`index.html no longer loads ./${vendored}`);
  }
  await access(path.join(kitDir, vendored));
}
if (/<script\b[^>]*\bsrc=(['"])https?:/i.test(shell)) {
  throw new Error('index.html loads a third-party script; the kit is served from this repository only');
}

const declared = new Map();
const blocks = [];

for (const source of SOURCES) {
  const raw = (await readFile(path.join(kitDir, source), 'utf8')).replace(/\r\n/g, '\n');
  const compiled = transform(raw, source).replace(/\s+$/, '');

  for (const name of topLevelBindings(raw)) {
    const owner = declared.get(name);
    if (owner) {
      throw new Error(
        `${source} declares "${name}" at the top level, and so does ${owner}. ` +
        'These become classic scripts sharing one global scope, so the second ' +
        'declaration throws and every script after it is skipped. Rename one — ' +
        'the screens alias theirs (useDevState, usePrepState) for this reason.'
      );
    }
    declared.set(name, source);
  }

  // A literal </script> inside the compiled code would end the block early. It
  // does not appear today; if a source ever grows one, splitting the token is a
  // silent-corruption bug waiting to happen, so refuse instead.
  if (/<\/script/i.test(compiled)) {
    throw new Error(`${source} contains a literal </script>, which cannot be inlined safely`);
  }

  blocks.push([
    '<script>',
    // Babel emitted this for every block; keeping it means the compiled page
    // runs under the same semantics the CDN page did.
    "'use strict';",
    `// ---- ${source} — compiled from source; edit the .jsx and re-run the assembler ----`,
    compiled,
    '</script>',
  ].join('\n'));
}

const generated = [
  START,
  '',
  blocks.join('\n'),
  '',
  END,
].join('\n');

const assembled = shell.slice(0, startAt) + generated + shell.slice(endAt + END.length);
const output = eol === '\r\n' ? assembled.replace(/\n/g, '\r\n') : assembled;

if (checkOnly) {
  if (output !== original) {
    console.error(
      'ui-md3/design-system/ui_kits/bambu-studio/index.html is out of sync with its .jsx sources.\n' +
      'Run: node ui-md3/scripts/assemble-ui-kit.mjs --write'
    );
    process.exit(1);
  }
  console.log(`UI kit index.html is synchronized with its ${SOURCES.length} .jsx sources`);
} else {
  await writeFile(indexPath, output, 'utf8');
  console.log(`Assembled ui-md3/design-system/ui_kits/bambu-studio/index.html from ${SOURCES.length} .jsx sources`);
}

/**
 * Names a source binds at the top level with const/let/class, including every
 * name in a destructuring pattern. `var` and `function` are deliberately absent:
 * both may legally be redeclared across classic scripts.
 */
function topLevelBindings(source) {
  const names = [];
  for (const match of source.matchAll(TOP_LEVEL_DECLARATION)) {
    const head = match[0].replace(/^(?:const|let|class)\s+/, '');
    if (!head.startsWith('{')) {
      names.push(head);
      continue;
    }
    for (const binding of head.slice(1, -1).matchAll(BINDING_NAME)) {
      // `const { useState: useAppState }` binds useAppState, not useState.
      names.push(binding[2] || binding[1]);
    }
  }
  return names;
}
