import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';import {execFileSync,spawnSync} from 'node:child_process';import {tmpdir} from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {compileFixture} from './native_fixture_compiler.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),revision=process.argv.find(x=>x.startsWith('--baseline='))?.slice(11),file='src/slic3r/GUI/AMSDryControl.cpp';const source=revision?execFileSync('git',['show',revision+':'+file],{cwd:root,encoding:'utf8'}):readFileSync(path.join(root,file),'utf8');
function method(signature){const start=source.indexOf(signature),open=source.indexOf('{',start);if(start<0)throw new Error('Missing method');const re=/\/\*[\s\S]*?\*\/|\/\/[^\n]*|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|[{}]/g;re.lastIndex=open;let depth=0;for(let m;(m=re.exec(source));){if(m[0]==='{')depth++;if(m[0]==='}'&&!--depth)return source.slice(start,m.index+1);}throw new Error('Unterminated method');}
const methods=method('wxBoxSizer* AMSDryCtrWin::create_right_panel')+'\n'+method('void AMSDryCtrWin::update_normal_state');
const cppText=`#include <iostream>
#include <vector>
constexpr int wxHORIZONTAL=0,wxEXPAND=1,wxBOTTOM=2;struct wxPanel{};
struct wxBoxSizer{bool shown=true;std::vector<wxBoxSizer*>children;wxBoxSizer(int){}void Add(wxBoxSizer*s,int,int){children.push_back(s);}void Insert(int pos,wxBoxSizer*s,int,int,int){children.insert(children.begin()+pos,s);}void Show(bool v){shown=v;}bool reaches(wxBoxSizer*target)const{if(!shown)return false;if(this==target)return true;for(auto*c:children)if(c->reaches(target))return true;return false;}};
struct Value{bool IsEmpty()const{return false;}};struct Control{bool shown=true,enabled=true;void Show(bool b){shown=b;}void Hide(){shown=false;}void Enable(bool b=true){enabled=b;}void Disable(){enabled=false;}void SetEditable(bool){}Control*GetTextCtrl(){return this;}Value GetValue(){return {};}};
struct DevAms{int state=0;};
struct AMSDryCtrWin{wxBoxSizer normal{0},unavailable{0},error{0};wxBoxSizer*m_normal_state_sizer=nullptr,*m_cannot_dry_sizer=nullptr,*m_dry_error_sizer=nullptr;Control next,description,trays,temperature,time,stop,start;Control*m_next_button=&next,*m_normal_description=&description,*m_trays_combo=&trays,*m_temperature_input=&temperature,*m_time_input=&time,*m_stop_button=&stop,*m_start_button=&start;int FromDIP(int v){return v;}wxBoxSizer*create_normal_state_panel(wxPanel*){return &normal;}wxBoxSizer*create_cannot_dry_panel(wxPanel*){return &unavailable;}wxBoxSizer*create_drying_error_panel(wxPanel*){return &error;}bool is_dry_ctr_idle(DevAms*d){return d->state==0;}bool is_dry_ctr_err(DevAms*d){return d->state==1;}void update_normal_description(DevAms*){}wxBoxSizer*create_right_panel(wxPanel*);void update_normal_state(DevAms*);};
${methods}
int main(){AMSDryCtrWin owner;wxPanel panel;auto*root=owner.create_right_panel(&panel);int failed=0;auto check=[&](bool v,const char*n){std::cout<<(v?"PASS ":"FAIL ")<<n<<'\\n';failed+=!v;};check(!root->reaches(owner.m_dry_error_sizer),"disclosure hidden initially");DevAms dev;dev.state=1;owner.update_normal_state(&dev);check(root->reaches(owner.m_dry_error_sizer)&&owner.stop.shown&&!owner.next.shown,"error disclosure reachable through actual owner with stop retained");dev.state=0;owner.update_normal_state(&dev);check(!root->reaches(owner.m_dry_error_sizer)&&owner.next.shown&&!owner.stop.shown,"idle hides disclosure and retains existing actions");delete root;std::cout<<3-failed<<"/3 cases passed\\n";return failed?1:0;}
`;
const output=mkdtempSync(path.join(tmpdir(),'bambustudio-drying-owner-')),cpp=path.join(output,'fixture.cpp'),exe=path.join(output,'fixture.exe');writeFileSync(cpp,cppText);console.log('Production source: '+(revision??'current'));console.log('Task-owned output: '+output);const compile=compileFixture({source:cpp,exe,cwd:output});if(compile.error)throw compile.error;if(compile.status!==0)process.exit(compile.status??1);const run=spawnSync(exe,[],{cwd:output,stdio:'inherit'});if(run.error)throw run.error;process.exit(run.status??1);
