import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {execFileSync} from 'node:child_process';
const base='50715f4355e8b845042bd4809bac2da2ce5c40f4',path='src/slic3r/GUI/AMSDryControl.cpp';
const revision=process.argv.find(x=>x.startsWith('--baseline='))?.slice(11);
const read=rev=>(rev?execFileSync('git',['show',rev+':'+path],{encoding:'utf8'}):readFileSync(path,'utf8')).replaceAll('\r\n','\n');
const s=read(revision),old=read(base);
function body(source,start){const tokens=/\/\*[\s\S]*?\*\/|\/\/[^\n]*|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|[{}]/g;tokens.lastIndex=source.indexOf('{',start);let depth=0;for(let m;(m=tokens.exec(source));){if(m[0]==='{')depth++;if(m[0]==='}'&&!--depth)return source.slice(start,m.index+1);}throw new Error('Missing method');}
function methods(source){const found=[];for(const m of source.matchAll(/^\w[^\n]*AMSDryCtrWin::([\w~]+)\(/gm)){if(m[1].startsWith('create')||m[1]==='queue_layout_refresh')continue;found.push([m[1],body(source,m.index).replace(/^[ \t]*queue_layout_refresh\(\);\n/gm,'')]);}return found;}
function bindings(source){return [...source.matchAll(/\bBind\(/g)].map(m=>{const start=m.index;let depth=0;const tokens=/"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|[()]/g;tokens.lastIndex=start+4;for(let t;(t=tokens.exec(source));){if(t[0]==='(')depth++;if(t[0]===')'&&!--depth)return source.slice(start,t.index+1);}throw new Error('Missing binding');}).filter(x=>!x.startsWith('Bind(wxEVT_SIZE,'));}
test('all existing non-construction methods preserve hardware, state, timers and values',()=>{const a=methods(s),b=methods(old);assert.equal(a.length,b.length);for(let i=0;i<a.length;i++)assert.ok(a[i][1]===b[i][1],a[i][0]);assert.ok(methods(old).length>=20);});
test('all existing action bindings and literal strings remain exact',()=>{assert.deepEqual(bindings(s),bindings(old));const strings=x=>[...x.replace(/^#include.*$/gm,'').matchAll(/"(?:\\.|[^"\\])*"/g)].map(m=>m[0]);assert.deepEqual(strings(s),strings(old));});
test('status and settings have density-aware semantic card ownership',()=>{for(const x of ['new StaticBox(parent','MD3::Metrics::isCompact()','status_card->SetSizer(create_left_panel(status_card))','settings_card->SetSizer(create_right_panel(settings_card))','MD3::Role::SurfaceContainerLow','MD3::Role::OutlineVariant'])assert.ok(s.includes(x),x);});
test('atomic fields, guide and actions wrap inside three scroll-owned pages',()=>{for(const x of ['input_sizer = new wxWrapSizer','buttons_container = new wxWrapSizer','guide_sizer = new wxWrapSizer','content_sizer = new wxWrapSizer'])assert.ok(s.includes(x),x);assert.equal((s.match(/new MD3ScrolledWindow\(m_main_simplebook/g)||[]).length,3);assert.ok(s.includes('static_cast<wxScrolledWindow*>(page)->FitInside()'));});
test('button variants and typography expose primary, secondary and destructive hierarchy',()=>{for(const x of ['Button::Variant::Danger','Button::Variant::Outlined','Button::Variant::Filled','titleLabel->SetFont(Label::Body_12)','dataLabel->SetFont(Label::Head_20)'])assert.ok(s.includes(x),x);});
test('negative hardware mutation is detected',()=>{assert.notDeepEqual(methods(s),methods(s.replace('CtrlAmsStartDryingHour','CtrlAmsStopDrying')));assert.notDeepEqual(bindings(s),bindings(s.replace('std::chrono::seconds(2)','std::chrono::seconds(1)')));});
