import {mkdtempSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const output=mkdtempSync(path.join(tmpdir(),'bambustudio-calibration-layout-'));
const exe=path.join(output,'fixture.exe');
console.log('Task-owned output: '+output);
const compile=spawnSync('cl.exe',['/nologo','/std:c++17','/EHsc','/W4','/I'+root,path.join(root,'tests/calibration_layout_fixture.cpp'),'/Fe:'+exe,'/Fo:'+path.join(output,'fixture.obj')],{cwd:output,stdio:'inherit'});
if(compile.error) throw compile.error;
if(compile.status!==0) process.exit(compile.status ?? 1);
const run=spawnSync(exe,[],{cwd:output,stdio:'inherit'});
if(run.error) throw run.error;
process.exit(run.status ?? 1);
