import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';
import {execFileSync,spawnSync} from 'node:child_process';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {compileFixture} from './native_fixture_compiler.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const revision=process.argv.find(x=>x.startsWith('--baseline='))?.slice(11);
const read=file=>revision?execFileSync('git',['show',revision+':src/slic3r/GUI/'+file],{cwd:root,encoding:'utf8'}):readFileSync(path.join(root,'src/slic3r/GUI',file),'utf8');
const definition=read('CalibrationWizardPage.hpp').match(/^#define MIN_CALIBRATION_PAGE_WIDTH[^\r\n]*/m)?.[0];
const page=read('CalibrationWizardPage.cpp').slice(read('CalibrationWizardPage.cpp').indexOf('CalibrationWizardPage::CalibrationWizardPage'));
const tips=read('CalibrationWizardPresetPage.cpp').slice(read('CalibrationWizardPresetPage.cpp').indexOf('CaliPresetTipsPanel::CaliPresetTipsPanel'));
const pageInit=page.match(/SetMinSize\(\{ MIN_CALIBRATION_PAGE_WIDTH, -1 \}\);/)?.[0];
const tipsInit=tips.match(/this->SetMinSize\(wxSize\(MIN_CALIBRATION_PAGE_WIDTH, -1\)\);/)?.[0];
if(!definition||!pageInit||!tipsInit)throw new Error('Missing actual page minimum initializer');
const output=mkdtempSync(path.join(tmpdir(),'bambustudio-calibration-minimum-'));
const cpp=path.join(output,'fixture.cpp'),exe=path.join(output,'fixture.exe');
const fixture=readFileSync(path.join(root,'tests/calibration_minimum_fixture.cpp'),'utf8').replace('// PRODUCTION_MINIMUM',definition).replace('/* PAGE_INITIALIZER */',pageInit).replace('/* TIPS_INITIALIZER */',tipsInit);
writeFileSync(cpp,fixture);console.log('Production initialization: '+(revision??'current working source'));console.log('Task-owned output: '+output);
const compile=compileFixture({source:cpp,exe,cwd:output});
if(compile.error)throw compile.error;if(compile.status!==0)process.exit(compile.status??1);
const run=spawnSync(exe,[],{cwd:output,stdio:'inherit'});if(run.error)throw run.error;process.exit(run.status??1);
