[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $PayloadDir,

    [Parameter(Mandatory = $true)]
    [string] $OutputPath
)

$ErrorActionPreference = 'Stop'

$payloadRootItem = Get-Item -LiteralPath $PayloadDir -Force
if ($payloadRootItem.Attributes -band [System.IO.FileAttributes]::ReparsePoint) {
    throw "Payload root is an unsupported reparse point '$($payloadRootItem.FullName)'."
}

$payloadRoot = $payloadRootItem.FullName.TrimEnd('\', '/')
$outputFullPath = [System.IO.Path]::GetFullPath($OutputPath)

if ($outputFullPath.StartsWith($payloadRoot + [System.IO.Path]::DirectorySeparatorChar, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw 'The generated include must be written outside the payload directory.'
}

function ConvertTo-NsisLiteral {
    param([Parameter(Mandatory = $true)][string] $RelativePath)

    if ([System.IO.Path]::IsPathRooted($RelativePath) -or
        $RelativePath -eq '..' -or
        $RelativePath.StartsWith('..\', [System.StringComparison]::Ordinal) -or
        $RelativePath.Contains("`r") -or
        $RelativePath.Contains("`n") -or
        $RelativePath.Contains('"')) {
        throw "Unsafe payload path '$RelativePath'."
    }

    return $RelativePath.Replace('$', '$$')
}

$entries = @(Get-ChildItem -LiteralPath $payloadRoot -Recurse -Force)
$reparsePoints = @($entries | Where-Object { $_.Attributes -band [System.IO.FileAttributes]::ReparsePoint })
if ($reparsePoints.Count -ne 0) {
    throw "Payload contains unsupported reparse point '$($reparsePoints[0].FullName)'."
}

$directories = @(
    $entries |
        Where-Object { $_.PSIsContainer } |
        ForEach-Object {
            $relativePath = [System.IO.Path]::GetRelativePath($payloadRoot, $_.FullName).Replace('/', '\')
            [pscustomobject]@{
                RelativePath = $relativePath
                Depth = ($relativePath -split '\\').Count
            }
        } |
        Sort-Object Depth, RelativePath -Descending
)

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('; Generated by GenerateUninstallInclude.ps1. Do not edit.')
$lines.Add('!macro BambuMD3AssertDestinationPaths')
$lines.Add('  !insertmacro AssertNotReparse "${PRODUCT_INSTALL_DIR}"')
foreach ($directory in @($directories | Sort-Object Depth, RelativePath)) {
    $literalPath = ConvertTo-NsisLiteral -RelativePath $directory.RelativePath
    $lines.Add(('  !insertmacro AssertNotReparse "${{PRODUCT_INSTALL_DIR}}\{0}"' -f $literalPath))
}
foreach ($file in @($entries | Where-Object { -not $_.PSIsContainer } | Sort-Object FullName)) {
    $relativePath = [System.IO.Path]::GetRelativePath($payloadRoot, $file.FullName).Replace('/', '\')
    $literalPath = ConvertTo-NsisLiteral -RelativePath $relativePath
    $lines.Add(('  !insertmacro AssertNotReparse "${{PRODUCT_INSTALL_DIR}}\{0}"' -f $literalPath))
}
$lines.Add('  !insertmacro AssertNotReparse "${PRODUCT_INSTALL_DIR}\Uninstall.exe"')
$lines.Add('!macroend')
$lines.Add('')

$lines.Add('!macro BambuMD3DeletePayloadFiles')
foreach ($file in @($entries | Where-Object { -not $_.PSIsContainer } | Sort-Object FullName)) {
    $relativePath = [System.IO.Path]::GetRelativePath($payloadRoot, $file.FullName).Replace('/', '\')
    $literalPath = ConvertTo-NsisLiteral -RelativePath $relativePath
    $lines.Add(('  Delete "${{PRODUCT_INSTALL_DIR}}\{0}"' -f $literalPath))
}
$lines.Add('!macroend')
$lines.Add('')

$lines.Add('!macro BambuMD3RemovePayloadDirectories')
foreach ($directory in $directories) {
    $literalPath = ConvertTo-NsisLiteral -RelativePath $directory.RelativePath
    $lines.Add(('  RMDir "${{PRODUCT_INSTALL_DIR}}\{0}"' -f $literalPath))
}
$lines.Add('  RMDir "${PRODUCT_INSTALL_DIR}"')
$lines.Add('!macroend')

$outputDirectory = Split-Path -Parent $outputFullPath
if ($outputDirectory) {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
}
$lines | Set-Content -LiteralPath $outputFullPath -Encoding utf8

Write-Output "Generated ownership, reparse-guard, and uninstall macros at $outputFullPath."
