[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $PayloadDir,

    [Parameter(Mandatory = $true)]
    [string] $OutputPath
)

$ErrorActionPreference = 'Stop'

$payloadRootItem = Get-Item -LiteralPath $PayloadDir -Force
if ($payloadRootItem.Attributes -band [System.IO.FileAttributes]::ReparsePoint) {
    throw "Payload root is an unsupported reparse point '$($payloadRootItem.FullName)'."
}

$payloadRoot = $payloadRootItem.FullName.TrimEnd('\', '/')
$outputFullPath = [System.IO.Path]::GetFullPath($OutputPath)

if ($outputFullPath.StartsWith($payloadRoot + [System.IO.Path]::DirectorySeparatorChar, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw 'The generated include must be written outside the payload directory.'
}

function ConvertTo-NsisLiteral {
    param([Parameter(Mandatory = $true)][string] $RelativePath)

    if ([System.IO.Path]::IsPathRooted($RelativePath) -or
        $RelativePath -eq '..' -or
        $RelativePath.StartsWith('..\', [System.StringComparison]::Ordinal) -or
        $RelativePath.Contains("`r") -or
        $RelativePath.Contains("`n") -or
        $RelativePath.Contains('"')) {
        throw "Unsafe payload path '$RelativePath'."
    }

    return $RelativePath.Replace('$', '$$')
}

$entries = @(Get-ChildItem -LiteralPath $payloadRoot -Recurse -Force)
$reparsePoints = @($entries | Where-Object { $_.Attributes -band [System.IO.FileAttributes]::ReparsePoint })
if ($reparsePoints.Count -ne 0) {
    throw "Payload contains unsupported reparse point '$($reparsePoints[0].FullName)'."
}

# The application's software-GL fallback copies mesa\opengl32.dll and
# mesa\libgallium_wgl.dll beside bambu-studio.exe at runtime (see
# docs/features/windows/software-gl-fallback.md). Those runtime copies are
# owned byproducts of the shipped payload, so when the payload carries the
# mesa fallback pair, the uninstaller must also guard and delete the root
# copies — otherwise an uninstall after the fallback fired would fail closed
# on "unknown paths". NSIS Delete on a never-created file is a no-op.
$softGlRuntimeCopies = @()
$payloadRelativeFiles = @(
    $entries |
        Where-Object { -not $_.PSIsContainer } |
        ForEach-Object { [System.IO.Path]::GetRelativePath($payloadRoot, $_.FullName).Replace('/', '\') }
)
$mesaFallbackPair = @('mesa\opengl32.dll', 'mesa\libgallium_wgl.dll')
$payloadHasMesaFallback = @(
    $mesaFallbackPair | Where-Object {
        $needle = $_
        $payloadRelativeFiles | Where-Object { $_.Equals($needle, [System.StringComparison]::OrdinalIgnoreCase) }
    }
).Count -eq $mesaFallbackPair.Count
if ($payloadHasMesaFallback) {
    $softGlRuntimeCopies = @('opengl32.dll', 'libgallium_wgl.dll') | Where-Object {
        $candidate = $_
        -not ($payloadRelativeFiles | Where-Object { $_.Equals($candidate, [System.StringComparison]::OrdinalIgnoreCase) })
    }
}

$reservedUninstallerPaths = @(
    $entries | Where-Object {
        [System.IO.Path]::GetRelativePath($payloadRoot, $_.FullName).Equals(
            'Uninstall.exe',
            [System.StringComparison]::OrdinalIgnoreCase
        )
    }
)
if ($reservedUninstallerPaths.Count -ne 0) {
    throw "Payload contains reserved installer path '$($reservedUninstallerPaths[0].FullName)'."
}

$directories = @(
    $entries |
        Where-Object { $_.PSIsContainer } |
        ForEach-Object {
            $relativePath = [System.IO.Path]::GetRelativePath($payloadRoot, $_.FullName).Replace('/', '\')
            [pscustomobject]@{
                RelativePath = $relativePath
                Depth = ($relativePath -split '\\').Count
            }
        } |
        Sort-Object Depth, RelativePath -Descending
)

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('; Generated by GenerateUninstallInclude.ps1. Do not edit.')
$lines.Add('!macro BambuMD3AssertDestinationPaths')
$lines.Add('  !insertmacro AssertNotReparse "${PRODUCT_INSTALL_ROOT}"')
$lines.Add('  !insertmacro AssertNotReparse "${PRODUCT_PROGRAMS_DIR}"')
$lines.Add('  !insertmacro AssertNotReparse "${PRODUCT_INSTALL_DIR}"')
$lines.Add('  !insertmacro AssertNotReparse "${PRODUCT_SHORTCUT_ROOT}"')
$lines.Add('  !insertmacro AssertNotReparse "${PRODUCT_SHORTCUT_DIR}"')
$lines.Add('  !insertmacro AssertNotReparse "${PRODUCT_SHORTCUT_DIR}\Bambu Studio MD3.lnk"')
$lines.Add('  !insertmacro AssertNotReparse "${PRODUCT_SHORTCUT_DIR}\Uninstall Bambu Studio MD3.lnk"')
foreach ($directory in @($directories | Sort-Object Depth, RelativePath)) {
    $literalPath = ConvertTo-NsisLiteral -RelativePath $directory.RelativePath
    $lines.Add(('  !insertmacro AssertNotReparse "${{PRODUCT_INSTALL_DIR}}\{0}"' -f $literalPath))
}
foreach ($file in @($entries | Where-Object { -not $_.PSIsContainer } | Sort-Object FullName)) {
    $relativePath = [System.IO.Path]::GetRelativePath($payloadRoot, $file.FullName).Replace('/', '\')
    $literalPath = ConvertTo-NsisLiteral -RelativePath $relativePath
    $lines.Add(('  !insertmacro AssertNotReparse "${{PRODUCT_INSTALL_DIR}}\{0}"' -f $literalPath))
}
foreach ($runtimeCopy in $softGlRuntimeCopies) {
    $literalPath = ConvertTo-NsisLiteral -RelativePath $runtimeCopy
    $lines.Add(('  !insertmacro AssertNotReparse "${{PRODUCT_INSTALL_DIR}}\{0}"' -f $literalPath))
}
$lines.Add('  !insertmacro AssertNotReparse "${PRODUCT_INSTALL_DIR}\Uninstall.exe"')
$lines.Add('!macroend')
$lines.Add('')

$lines.Add('!macro BambuMD3DeletePayloadFiles')
foreach ($file in @($entries | Where-Object { -not $_.PSIsContainer } | Sort-Object FullName)) {
    $relativePath = [System.IO.Path]::GetRelativePath($payloadRoot, $file.FullName).Replace('/', '\')
    $literalPath = ConvertTo-NsisLiteral -RelativePath $relativePath
    $lines.Add(('  Delete "${{PRODUCT_INSTALL_DIR}}\{0}"' -f $literalPath))
}
foreach ($runtimeCopy in $softGlRuntimeCopies) {
    $literalPath = ConvertTo-NsisLiteral -RelativePath $runtimeCopy
    $lines.Add(('  Delete "${{PRODUCT_INSTALL_DIR}}\{0}"' -f $literalPath))
}
$lines.Add('!macroend')
$lines.Add('')

$lines.Add('!macro BambuMD3RemovePayloadDirectories')
foreach ($directory in $directories) {
    $literalPath = ConvertTo-NsisLiteral -RelativePath $directory.RelativePath
    $lines.Add(('  RMDir "${{PRODUCT_INSTALL_DIR}}\{0}"' -f $literalPath))
}
$lines.Add('  RMDir "${PRODUCT_INSTALL_DIR}"')
$lines.Add('!macroend')

$outputDirectory = Split-Path -Parent $outputFullPath
if ($outputDirectory) {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
}
$lines | Set-Content -LiteralPath $outputFullPath -Encoding utf8

Write-Output "Generated ownership, reparse-guard, and uninstall macros at $outputFullPath."
