#include <catch_main.hpp>

#include "libslic3r/Markdown.hpp"
#include "nlohmann/json.hpp"

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

// Completeness guard for the in-app documentation bundle.
//
// resources/docs/bundle.json is generated by cmake/modules/BundleDocs.cmake
// from docs/features/**/*.md and committed. Bundling drops a file exactly as
// easily as it includes one, so this suite re-derives the same view straight
// from the tree and fails the build when the bundle is missing an article,
// carries one that no longer exists, has a drifted title, or a stale body.
// The fix is always the same: regenerate the snapshot.
//
//   cmake -DDOCS_SOURCE=docs -DDOCS_OUTPUT=resources/docs -P cmake/modules/BundleDocs.cmake

#ifndef DOCS_BUNDLE_TEST_SOURCE_DIR
#error "DOCS_BUNDLE_TEST_SOURCE_DIR must identify the repository root"
#endif

namespace {

const std::filesystem::path kSourceRoot{DOCS_BUNDLE_TEST_SOURCE_DIR};

std::string read_file(const std::filesystem::path &path)
{
    std::ifstream in(path, std::ios::binary);
    REQUIRE(in.good());
    std::stringstream buffer;
    buffer << in.rdbuf();
    std::string text = buffer.str();
    // The bundler normalises CRLF, so compare the same way.
    std::string out;
    out.reserve(text.size());
    for (size_t i = 0; i < text.size(); ++i) {
        if (text[i] == '\r' && i + 1 < text.size() && text[i + 1] == '\n') continue;
        out.push_back(text[i]);
    }
    return out;
}

struct DiskArticle
{
    std::string category;
    bool        index;
    std::string title;
    std::string body;
};

std::map<std::string, DiskArticle> articles_on_disk()
{
    std::map<std::string, DiskArticle> out; // repo-relative path -> article
    const std::filesystem::path docs = kSourceRoot / "docs" / "features";
    REQUIRE(std::filesystem::is_directory(docs));
    for (const auto &entry : std::filesystem::recursive_directory_iterator(docs)) {
        if (!entry.is_regular_file() || entry.path().extension() != ".md") continue;
        const std::string rel  = std::filesystem::relative(entry.path(), kSourceRoot).generic_string();
        const std::string body = read_file(entry.path());
        DiskArticle a;
        a.category = entry.path().parent_path().filename().string();
        a.index    = entry.path().filename() == "README.md";
        a.title    = Slic3r::Markdown::first_heading(body);
        a.body     = body;
        out.emplace(rel, std::move(a));
    }
    return out;
}

nlohmann::json load_bundle()
{
    const std::filesystem::path bundle = kSourceRoot / "resources" / "docs" / "bundle.json";
    INFO("bundle missing: " << bundle.string() << " (run BundleDocs.cmake)");
    REQUIRE(std::filesystem::is_regular_file(bundle));
    std::ifstream in(bundle, std::ios::binary);
    nlohmann::json j;
    REQUIRE_NOTHROW(in >> j);
    return j;
}

} // namespace

TEST_CASE("Docs bundle has the expected shape", "[DocsBundle][schema]")
{
    const nlohmann::json j = load_bundle();
    REQUIRE(j.is_object());
    REQUIRE(j.value("version", 0) == 1);
    REQUIRE(j.value("source", "") == "docs/features");
    REQUIRE(j.contains("articles"));
    REQUIRE(j["articles"].is_array());
    for (const auto &a : j["articles"]) {
        INFO(a.dump());
        REQUIRE(a.is_object());
        for (const char *key : {"path", "category", "title", "body"}) {
            REQUIRE(a.contains(key));
            REQUIRE(a[key].is_string());
        }
        REQUIRE(a.contains("index"));
        REQUIRE(a["index"].is_boolean());
        REQUIRE(a["path"].get<std::string>().rfind("docs/features/", 0) == 0);
    }
}

TEST_CASE("Every article on disk is in the bundle, and nothing else is", "[DocsBundle][completeness]")
{
    const std::map<std::string, DiskArticle> disk   = articles_on_disk();
    const nlohmann::json                     bundle = load_bundle();
    REQUIRE(disk.size() >= 40); // the tree really was scanned

    std::set<std::string> bundled;
    for (const auto &a : bundle["articles"]) {
        const std::string path = a["path"].get<std::string>();
        INFO("bundled twice: " << path);
        REQUIRE(bundled.insert(path).second);
        const auto it = disk.find(path);
        INFO("bundled article no longer on disk: " << path << " (regenerate the bundle)");
        REQUIRE(it != disk.end());
    }
    for (const auto &[path, article] : disk) {
        INFO("article on disk missing from the bundle: " << path << " (" << article.title << ")");
        REQUIRE(bundled.count(path) == 1);
    }
    REQUIRE(bundled.size() == disk.size());
}

TEST_CASE("Bundled titles, categories and bodies match the tree byte for byte", "[DocsBundle][completeness]")
{
    const std::map<std::string, DiskArticle> disk   = articles_on_disk();
    const nlohmann::json                     bundle = load_bundle();
    for (const auto &a : bundle["articles"]) {
        const std::string path = a["path"].get<std::string>();
        const auto        it   = disk.find(path);
        if (it == disk.end()) continue; // reported by the completeness case
        INFO("title drifted for " << path << ": disk='" << it->second.title << "' bundle='" << a["title"].get<std::string>() << "'");
        REQUIRE(a["title"].get<std::string>() == it->second.title);
        INFO("category drifted for " << path);
        REQUIRE(a["category"].get<std::string>() == it->second.category);
        REQUIRE(a["index"].get<bool>() == it->second.index);
        INFO("body is stale for " << path << " (regenerate the bundle)");
        REQUIRE(a["body"].get<std::string>() == it->second.body);
    }
}

TEST_CASE("Every article has a title and renders without raw markup leaking", "[DocsBundle][render]")
{
    const nlohmann::json bundle = load_bundle();
    for (const auto &a : bundle["articles"]) {
        const std::string path = a["path"].get<std::string>();
        INFO(path);
        REQUIRE_FALSE(a["title"].get<std::string>().empty());
        const std::string html = Slic3r::Markdown::render_to_html(a["body"].get<std::string>());
        REQUIRE_FALSE(html.empty());
        // The renderer never passes source HTML through: a <script> in an
        // article body would have to appear escaped.
        REQUIRE(html.find("<script") == std::string::npos);
        // Rendering is deterministic.
        REQUIRE(html == Slic3r::Markdown::render_to_html(a["body"].get<std::string>()));
    }
}

TEST_CASE("Every relative image an article references was bundled as an asset", "[DocsBundle][assets]")
{
    const nlohmann::json bundle = load_bundle();
    const std::filesystem::path assets = kSourceRoot / "resources" / "docs" / "assets";
    size_t checked = 0;
    for (const auto &a : bundle["articles"]) {
        const std::string path = a["path"].get<std::string>();
        const std::string body = a["body"].get<std::string>();
        std::vector<std::string> refs;
        Slic3r::Markdown::RenderOptions opts;
        opts.resolve_image = [&refs](const std::string &d) { refs.push_back(d); return std::string(); };
        Slic3r::Markdown::render_to_html(body, opts);
        const std::filesystem::path article_dir = (kSourceRoot / path).parent_path();
        for (const std::string &ref : refs) {
            if (ref.find("://") != std::string::npos) continue;
            const std::filesystem::path resolved = std::filesystem::weakly_canonical(article_dir / ref);
            const std::filesystem::path rel      = std::filesystem::relative(resolved, kSourceRoot / "docs");
            INFO(path << " references " << ref << " -> expected asset " << (assets / rel).string());
            REQUIRE(std::filesystem::is_regular_file(assets / rel));
            ++checked;
        }
    }
    REQUIRE(checked >= 1); // the docs tree does carry images today
}

TEST_CASE("Article-to-article links resolve to bundled articles", "[DocsBundle][links]")
{
    const nlohmann::json bundle = load_bundle();
    std::set<std::string> paths;
    for (const auto &a : bundle["articles"]) paths.insert(a["path"].get<std::string>());

    for (const auto &a : bundle["articles"]) {
        const std::string path = a["path"].get<std::string>();
        std::vector<std::string> links;
        Slic3r::Markdown::RenderOptions opts;
        opts.resolve_link = [&links](const std::string &d) { links.push_back(d); return std::string(); };
        Slic3r::Markdown::render_to_html(a["body"].get<std::string>(), opts);
        const std::filesystem::path article_dir = std::filesystem::path(path).parent_path();
        for (const std::string &link : links) {
            if (link.find("://") != std::string::npos || link.rfind("mailto:", 0) == 0 || link.rfind('#', 0) == 0) continue;
            const std::string target = link.substr(0, link.find('#'));
            if (target.size() < 3 || target.compare(target.size() - 3, 3, ".md") != 0) continue;
            const std::string resolved = std::filesystem::weakly_canonical(kSourceRoot / article_dir / target).lexically_normal().generic_string();
            const std::string rel = std::filesystem::relative(resolved, kSourceRoot).generic_string();
            // Links that leave docs/features (README.md at the root, HANDOFF.md)
            // are external to the bundle and open on disk / in the browser.
            if (rel.rfind("docs/features/", 0) != 0) continue;
            INFO(path << " links to " << link << " which is not a bundled article");
            REQUIRE(paths.count(rel) == 1);
        }
    }
}
