#!/usr/bin/env python3
"""Render design/native-feature-gaps.md from design/native-feature-gaps.json.

    python3 scripts/md3/render-feature-gaps.py [--check]

The JSON ledger is the record. This page is a readable view of it. ``--check``
fails when the committed page differs from a fresh rendering.
"""
import argparse
import collections
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
LEDGER = ROOT / "design" / "native-feature-gaps.json"
PAGE = ROOT / "design" / "native-feature-gaps.md"
STATUSES = ("open", "landed", "verified")


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def render(ledger):
    gaps = ledger["gaps"]
    by_family = collections.defaultdict(list)
    for gap in gaps:
        by_family[gap["family"]].append(gap)
    totals = collections.Counter(gap["status"] for gap in gaps)
    lines = [
        "# Native feature gaps",
        "",
        "<!-- Generated by scripts/md3/render-feature-gaps.py from native-feature-gaps.json. Do not edit by hand. -->",
        "",
        ledger["scope"],
        "",
        f"Audit source commit: `{ledger['auditSourceCommit']}`. Completion claim: {'yes' if ledger['completionClaim'] else 'no'}.",
        "",
        "| Status | Meaning | Gaps |",
        "| --- | --- | ---: |",
    ]
    for status in STATUSES:
        lines.append(f"| {status} | {cell(ledger['statusMeaning'][status])} | {totals.get(status, 0)} |")
    lines += [f"| total | | {len(gaps)} |", "", "## Families", "",
              "| Group | Family | Audit status | Open | Landed | Verified |", "| --- | --- | --- | ---: | ---: | ---: |"]
    for family in ledger["families"]:
        counts = collections.Counter(gap["status"] for gap in by_family[family["id"]])
        lines.append(f"| {family['group']} | [{family['id']}](#{family['id']}) | {family['auditStatus']} | "
                     f"{counts.get('open', 0)} | {counts.get('landed', 0)} | {counts.get('verified', 0)} |")
    for family in ledger["families"]:
        lines += ["", f"## {family['id']}", "", cell(family["summary"]), "",
                  "| Gap | Size | Needs Windows | Status | Title | Landed in |", "| --- | --- | --- | --- | --- | --- |"]
        for gap in by_family[family["id"]]:
            landed = f"`{gap['landedIn'][:10]}`" if gap.get("landedIn") else ""
            lines.append(f"| `{gap['id']}` | {gap['size']} | {'yes' if gap['needsWindowsRuntime'] else 'no'} | "
                         f"{gap['status']} | {cell(gap['title'])} | {landed} |")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the page is stale")
    args = parser.parse_args()
    text = render(json.loads(LEDGER.read_text(encoding="utf-8")))
    if args.check:
        current = PAGE.read_text(encoding="utf-8") if PAGE.exists() else ""
        if current != text:
            print(f"{PAGE.relative_to(ROOT)} is stale; run scripts/md3/render-feature-gaps.py", file=sys.stderr)
            return 1
        print(f"{PAGE.relative_to(ROOT)} is current")
        return 0
    PAGE.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {PAGE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
