#ifndef slic3r_GUI_ChangelogDialog_hpp_
#define slic3r_GUI_ChangelogDialog_hpp_

#include "Widgets/MD3Dialog.hpp"

#include "libslic3r/Changelog.hpp"

#include <optional>
#include <string>
#include <vector>

class Button;
class Label;
class SearchField;
class wxCommandEvent;
class wxScrolledWindow;
class wxTextCtrl;

namespace Slic3r::GUI {

class ChangelogCalendarPopup;

// "What's new" — the in-app changelog viewer. Lists every release this fork
// has published (resources/changelog/changelog.json, generated by
// scripts/changelog/export-app-changelog.mjs) with its date, code name and the
// categorized commit lines between it and the previous release. Each line
// links its commit on GitHub.
//
// Filtering: a SearchField over entry text (plain text by default, regex via
// its builder) composes with an inclusive date range. The range is typed into
// two fields (ISO always, the locale's short order otherwise) or picked in an
// anchored calendar popover with month/year jump, range selection and presets.
// Invalid typed input is reported inline and left in the field.
//
// Copy and Export (Markdown or plain text) honour the active filters, state
// the exported range and keep every full commit SHA. Results are announced
// through the app's non-blocking notifications.
class ChangelogDialog final : public MD3Dialog
{
public:
    explicit ChangelogDialog(wxWindow *parent);
    ~ChangelogDialog() override;

    // Path of the bundled data file (resources/changelog/changelog.json).
    static std::string data_path();

    void on_dpi_changed(const wxRect &suggested_rect) override;

private:
    enum class Bound { From, To };

    void load_data();
    void build_ui();
    void apply_theme();

    // Re-run date + text filtering and rebuild the list.
    void apply_filters();
    void rebuild_list();
    void add_release_card(const Changelog::FilteredRelease &filtered, wxSizer *into);
    void update_status();

    // Typed dates: parse in the locale order, keep the text, report inline.
    Changelog::DateOrder locale_date_order() const;
    wxString             locale_date_hint() const;
    void                 on_date_typed(Bound bound);
    void                 set_range(const Changelog::DateRange &range, bool write_fields);
    void                 update_date_error();
    void                 open_calendar();

    Changelog::TextMatcher current_matcher() const;
    std::string            search_description() const;
    std::string            export_text(Changelog::ExportFormat format) const;

    void on_copy(wxCommandEvent &event);
    void on_export(wxCommandEvent &event);
    void show_toast(const wxString &text, bool error = false);

    std::optional<Changelog::Document>     m_document;
    std::string                            m_load_error;
    Changelog::DateRange                   m_range;
    std::vector<Changelog::FilteredRelease> m_filtered;
    // Bounds whose field text is not a date right now (kept on screen, unapplied).
    bool m_from_invalid = false;
    bool m_to_invalid   = false;
    // The list renders this many releases before offering "Show all".
    bool m_show_all = false;

    SearchField      *m_search          = nullptr;
    wxTextCtrl       *m_from_field      = nullptr;
    wxTextCtrl       *m_to_field        = nullptr;
    Button           *m_calendar_button = nullptr;
    Button           *m_preset_30       = nullptr;
    Button           *m_preset_year     = nullptr;
    Button           *m_preset_all      = nullptr;
    Label            *m_date_error      = nullptr;
    Label            *m_status          = nullptr;
    wxScrolledWindow *m_scroll          = nullptr;
    Button           *m_show_all_button = nullptr;
    Button           *m_copy_button     = nullptr;
    Button           *m_export_button   = nullptr;
    Button           *m_close_button    = nullptr;
    ChangelogCalendarPopup *m_calendar  = nullptr;
};

} // namespace Slic3r::GUI

#endif // slic3r_GUI_ChangelogDialog_hpp_
