# Compile diagnostics with logical source paths and embed only a PDB basename.
# This is producer metadata, not post-link binary rewriting.
if(MSVC AND CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    if(MSVC_VERSION LESS 1951)
        message(FATAL_ERROR "Release source-path mapping requires MSVC 19.51 or newer.")
    endif()
    get_filename_component(_bambu_source_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
    set(_bambu_path_flags "/experimental:deterministic")
    # Map repository content precisely, with a broader host-root mapping for
    # generated files, dependency caches and headers outside the source tree.
    set(_bambu_roots "${_bambu_source_root}" "${CMAKE_SOURCE_DIR}" "${CMAKE_BINARY_DIR}")
    set(_bambu_labels "source/BambuStudio" "source/${PROJECT_NAME}" "build/${PROJECT_NAME}")
    if(DEFINED ENV{USERPROFILE} AND NOT "$ENV{USERPROFILE}" STREQUAL "")
        list(APPEND _bambu_roots "$ENV{USERPROFILE}")
        list(APPEND _bambu_labels "build/host")
    endif()
    list(LENGTH _bambu_roots _bambu_root_count)
    math(EXPR _bambu_last_root "${_bambu_root_count} - 1")
    foreach(_bambu_index RANGE ${_bambu_last_root})
        list(GET _bambu_roots ${_bambu_index} _bambu_root)
        list(GET _bambu_labels ${_bambu_index} _bambu_label)
        file(TO_NATIVE_PATH "${_bambu_root}" _bambu_native_root)
        string(APPEND _bambu_path_flags " /pathmap:\"${_bambu_native_root}=${_bambu_label}\"")
    endforeach()
    string(APPEND CMAKE_C_FLAGS " ${_bambu_path_flags}")
    string(APPEND CMAKE_CXX_FLAGS " ${_bambu_path_flags}")
    foreach(_bambu_link_kind EXE SHARED MODULE)
        string(APPEND CMAKE_${_bambu_link_kind}_LINKER_FLAGS " /PDBALTPATH:%_PDB%")
    endforeach()
    set(BAMBU_RELEASE_SOURCE_PATH_POLICY "msvc-pathmap-v1" CACHE INTERNAL "Native release source-path policy")
endif()
