# Compile diagnostics with logical source paths and embed only a PDB basename.
# This is producer metadata, not post-link binary rewriting.
if(MSVC AND (CMAKE_C_COMPILER_ID STREQUAL "MSVC" OR CMAKE_CXX_COMPILER_ID STREQUAL "MSVC"))
    if(MSVC_VERSION LESS 1951)
        message(FATAL_ERROR "Release source-path mapping is enabled only for the inspected MSVC 19.51-or-newer baseline; older compiler compatibility has not been established.")
    endif()
    get_filename_component(_bambu_source_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
    set(_bambu_path_flags "/experimental:deterministic")
    # Map repository content precisely, with a broader host-root mapping for
    # generated files, dependency caches and headers outside the source tree.
    set(_bambu_roots "${_bambu_source_root}" "${CMAKE_SOURCE_DIR}" "${CMAKE_BINARY_DIR}")
    set(_bambu_labels "source/BambuStudio" "source/${PROJECT_NAME}" "build/${PROJECT_NAME}")
    if(DEFINED ENV{USERPROFILE} AND NOT "$ENV{USERPROFILE}" STREQUAL "")
        list(APPEND _bambu_roots "$ENV{USERPROFILE}")
        list(APPEND _bambu_labels "build/host")
    endif()
    set(_bambu_embedded_roots)
    set(_bambu_embedded_labels)
    # Emit the longest physical prefixes first, leaving the user-profile
    # fallback behind repository, child-project and generated-build roots.
    while(_bambu_roots)
        set(_bambu_longest_index 0)
        set(_bambu_longest_length -1)
        set(_bambu_index 0)
        foreach(_bambu_root IN LISTS _bambu_roots)
            string(LENGTH "${_bambu_root}" _bambu_length)
            if(_bambu_length GREATER _bambu_longest_length)
                set(_bambu_longest_length ${_bambu_length})
                set(_bambu_longest_index ${_bambu_index})
            endif()
            math(EXPR _bambu_index "${_bambu_index} + 1")
        endforeach()
        list(GET _bambu_roots ${_bambu_longest_index} _bambu_root)
        list(GET _bambu_labels ${_bambu_longest_index} _bambu_label)
        list(REMOVE_AT _bambu_roots ${_bambu_longest_index})
        list(REMOVE_AT _bambu_labels ${_bambu_longest_index})
        file(TO_CMAKE_PATH "${_bambu_root}" _bambu_forward_root)
        file(TO_NATIVE_PATH "${_bambu_root}" _bambu_native_root)
        list(APPEND _bambu_embedded_roots "${_bambu_native_root}")
        list(APPEND _bambu_embedded_labels "${_bambu_label}")
        # Source/header strings can use either separator form, or mix them
        # after the matched prefix. Do not assume compiler normalization.
        string(APPEND _bambu_path_flags " /pathmap:\"${_bambu_native_root}=${_bambu_label}\"")
        if(NOT _bambu_forward_root STREQUAL _bambu_native_root)
            list(APPEND _bambu_embedded_roots "${_bambu_forward_root}")
            list(APPEND _bambu_embedded_labels "${_bambu_label}")
            string(APPEND _bambu_path_flags " /pathmap:\"${_bambu_forward_root}=${_bambu_label}\"")
        endif()
    endwhile()
    # Generated diagnostic metadata is ordinary text, not a compiler macro.
    # Producers call this before C-string escaping, preserving every field
    # while substituting the same logical roots used by compilation.
    function(bambu_release_logical_text output text)
        set(_text "${text}")
        list(LENGTH _bambu_embedded_roots _count)
        if(_count GREATER 0)
            math(EXPR _last "${_count} - 1")
            foreach(_index RANGE ${_last})
                list(GET _bambu_embedded_roots ${_index} _physical)
                list(GET _bambu_embedded_labels ${_index} _logical)
                string(REPLACE "${_physical}" "${_logical}" _text "${_text}")
            endforeach()
        endif()
        set(${output} "${_text}" PARENT_SCOPE)
    endfunction()
    string(APPEND CMAKE_C_FLAGS " ${_bambu_path_flags}")
    string(APPEND CMAKE_CXX_FLAGS " ${_bambu_path_flags}")
    foreach(_bambu_link_kind EXE SHARED MODULE)
        string(APPEND CMAKE_${_bambu_link_kind}_LINKER_FLAGS " /PDBALTPATH:%_PDB%")
    endforeach()
    set(BAMBU_RELEASE_SOURCE_PATH_POLICY "msvc-pathmap-v1" CACHE INTERNAL "Native release source-path policy")
endif()
