function ClosePage() {
	var tSend = {};
	tSend['sequence_id'] = Math.round(new Date() / 1000);
	tSend['command'] = "close_page";
	SendWXMessage(JSON.stringify(tSend));
}

function isOwnedGuideLegacyAction(node) {
	if (!node || node.nodeType !== 1) return false;
	if (!node.hasAttribute('onclick') && !node.hasAttribute('onClick')) return false;
	return node.matches('div, span, img, a:not([href]), a[href="javascript:void(0)"]');
}

function labelLegacyGuideAction(node) {
	if (!isOwnedGuideLegacyAction(node)) return;

	if (node.matches('a')) {
		node.setAttribute('href', '#');
	} else {
		node.setAttribute('role', 'button');
	}
	node.setAttribute('data-guide-legacy-action', 'true');
	node.setAttribute('tabindex', '0');

	if (node.tagName === 'IMG' && !node.getAttribute('aria-label')) {
		var title = node.getAttribute('title');
		var alt = node.getAttribute('alt');
		node.setAttribute('aria-label', title || alt || 'Edit');
		node.setAttribute('alt', '');
	}
}

// One compatibility initializer covers legacy action nodes that are still
// generated by owned setup-guide scripts. Native controls remain untouched.
function initializeOwnedGuideActions(root) {
	var scope = root && root.querySelectorAll ? root : document;
	if (isOwnedGuideLegacyAction(scope)) labelLegacyGuideAction(scope);
	scope.querySelectorAll('[onclick], [onClick]').forEach(labelLegacyGuideAction);
}

document.addEventListener('keydown', function (event) {
	var target = event.target;
	if (!isOwnedGuideLegacyAction(target)) return;
	if (event.key === 'Enter' || event.key === ' ') {
		event.preventDefault();
		target.click();
	}
});

document.addEventListener('click', function (event) {
	var target = event.target && event.target.closest ? event.target.closest('a[data-guide-legacy-action="true"][href="#"]') : null;
	if (target) event.preventDefault();
});

document.addEventListener('DOMContentLoaded', function () {
	initializeOwnedGuideActions(document);
	if (typeof MutationObserver === 'function') {
		new MutationObserver(function (records) {
			records.forEach(function (record) {
				record.addedNodes.forEach(function (node) { initializeOwnedGuideActions(node); });
			});
		}).observe(document.body, { childList: true, subtree: true });
	}
});
